version: '3.8'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge