version: '3.8'
services:
  springboot-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-blue
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Seoul
    networks:
      - app-network
    restart: unless-stopped

  springboot-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-green
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Seoul
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge