version: '3.8'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge