version: '3.8'
services:
  springboot-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-blue
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - app-network

  springboot-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-green
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge